### ISSUE TITLE
AudioSegment.export should accept a file-like object

### ISSUE THREAD

**Issue by tibbe** [clo4/pydub-stubs#5]
`AudioSegment.export` actually accepts a file object (e.g. `io.BytesIO`), which you can see if you follow the code from https://github.com/jiaaro/pydub/blob/996cec42e9621701edb83354232b2c0ca0121560/pydub/audio_segment.py#L645 through https://github.com/jiaaro/pydub/blob/master/pydub/utils.py#L54. This also mentioned here: https://github.com/jiaaro/pydub/issues/220#issuecomment-335490578

However, the stub only accepts `_PathLike: TypeAlias = str | bytes | os.PathLike[Any] | pathlib.Path`.

**Comment by tibbe** [comment]
This is also true for `AudioSegment.from_file` for the same reason (i.e. it uses `_fd_or_path_or_tempfile`).

**Comment by clo4** [comment]
No idea how I missed this and that it somehow hasn't come up for years. Thank you for making the issue! Will have a new version with this fixed out very soon.

**Comment by clo4** [comment]
Version `0.25.1.3` is published. You can bump your version locally and it should work. Please let me know if you run into any issues :)

**Comment by tibbe** [comment]
Works great, thanks!
